In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("Salaries.csv")

C:\Users\MSII\AppData\Local\Temp\ipykernel_13028\91212481.py:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Salaries.csv")

SHAPE OF DATASET

In [6]:
df.shape

(148654, 13)

TOTAL NO OF ROWS

In [7]:
df.shape[0]

148654

TOTAL NO OF COLUMNS

In [8]:
df.shape[1]

13

DATATYPE OF EACH COLUMN

In [9]:
df.dtypes

Id                    int64
EmployeeName         object
JobTitle             object
BasePay              object
OvertimePay          object
OtherPay             object
Benefits             object
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status               object
dtype: object

TOTAL MEMORY REQUIREMENT

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

CHECK NULL VALUES

In [14]:
df.isnull()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,False,False,False,False,False,False,True,False,False,False,True,False,True
1,False,False,False,False,False,False,True,False,False,False,True,False,True
2,False,False,False,False,False,False,True,False,False,False,True,False,True
3,False,False,False,False,False,False,True,False,False,False,True,False,True
4,False,False,False,False,False,False,True,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,False,False,False,False,False,False,False,False,False,False,True,False,False
148650,False,False,False,False,False,False,False,False,False,False,True,False,True
148651,False,False,False,False,False,False,False,False,False,False,True,False,True
148652,False,False,False,False,False,False,False,False,False,False,True,False,True
148653,False,False,False,False,False,False,False,False,False,False,True,False,False

DROP ID NOTES AGENCY AND STATUS COLUMN

In [ ]:
df.drop(columns=["Id","Notes","Agency", "Status" ], inplace = True)

OVERALL STATS OF THE DATAFRAME

In [22]:
df.describe()

            TotalPay  TotalPayBenefits           Year
count  148654.000000     148654.000000  148654.000000
mean    74768.321972      93692.554811    2012.522643
std     50517.005274      62793.533483       1.117538
min      -618.130000       -618.130000    2011.000000
25%     36168.995000      44065.650000    2012.000000
50%     71426.610000      92404.090000    2013.000000
75%    105839.135000     132876.450000    2014.000000
max    567595.430000     567595.430000    2014.000000

TOP 5 OCCURRENCE OF THE EMPLOYEE NAME

In [25]:
df["EmployeeName"].value_counts().head()

EmployeeName
Kevin Lee       13
William Wong    11
Steven Lee      11
Richard Lee     11
John Chan        9
Name: count, dtype: int64

UNIQUE JOB TITLES

In [32]:
df["JobTitle"].nunique()

2159

TOTAL NO OF JOB TITLES CONTAIN CAPTAIN

In [44]:
len(df[df["JobTitle"].str.contains("CAPTAIN")])

141

ALL EMPLOYEES NAME FROM FIRE DEPARTMENT

In [43]:
df[df["JobTitle"].str.contains("FIRE DEPARTMENT", case = False)]["EmployeeName"]

4              PATRICK GARDNER
6                    ALSON LEE
8               MICHAEL MORRIS
9           JOANNE HAYES-WHITE
10               ARTHUR KENNEY
                  ...
32623             JAMES BARDEN
36162       Joanne Hayes-White
72926     Joanne M Hayes-White
102303          Robert E Evans
110535    Joanne M Hayes-White
Name: EmployeeName, Length: 226, dtype: object

FIND MIN, MAX, AND AVG BASEPAY

In [55]:
df["BasePay"] = pd.to_numeric(df["BasePay"],errors="coerce")
df["BasePay"].min()
df["BasePay"].max()
df["BasePay"].mean()

np.float64(66325.44884048769)